(#1088) Improve test coverage
yegor256/takes pull request #1094
Opened 2021-03-12 07:04 UTC by baudoliver7

For #1088

- Improve test coverage of packages xe, fork and tk

2021-03-14 01:39 UTC, andreoss requested changes

2021-03-14 05:35 UTC, baudoliver7 commented on src/test/java/org/takes/rs/xe/XeWhenTest.java
> +            IOUtils.toString(
@andreoss Done.

2021-03-14 05:36 UTC, baudoliver7 commented
@andreoss Please, see my new changes.

2021-03-14 08:44 UTC, andreoss commented
@baudoliver7 Sorry, I meant using cactoos instead of `IOUtils`.

2021-03-15 02:36 UTC, andreoss approved these changes

2021-03-22 09:16 UTC, baudoliver7 commented
@victornoel ping

2021-03-22 09:27 UTC, victornoel commented
@baudoliver7 I'm not involved in takes :)

2021-03-22 09:27 UTC, victornoel commented
@0crat status

2021-03-22 09:29 UTC, 0crat commented
> @0crat status ([here](https://github.com/yegor256/takes/issues/1094#issuecomment-803908494))

@victornoel This is what I know about this job in C3FFK3YAY, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1094](https://github.com/yegor256/takes/issues/1094) is [in scope](http://www.zerocracy.com/policy.html#14) for 10days
  * The role is `REV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [10days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @baudoliver7[/z](https://www.0crat.com/u/baudoliver7): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%231094%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

<!-- https://www.0crat.com/footprint/C3FFK3YAY/73ba3626-6494-4adf-962e-89f423361522, version: 0.55.1, hash: ${buildNumber} -->

2021-03-22 09:58 UTC, baudoliver7 commented
@victornoel Excuse me. it was a mistake. This ping was for @paulodamaso.

2021-06-23 21:10 UTC, paulodamaso commented
@rultor merge

2021-06-23 21:11 UTC, rultor commented
> @rultor merge

@paulodamaso OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24654-867161745)

2021-06-23 21:13 UTC, rultor commented
> @rultor merge

@baudoliver7 @paulodamaso Oops, I failed. You can see the full log [here](https://www.rultor.com/t/24654-867161745) (spent 2min)

```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 29127
+ echo '1.69.1 839260fab'
1.69.1 839260fab
+ date
Wed Jun 23 23:12:24 CEST 2021
+ uptime
 23:12:24 up 269 days,  7:18,  0 users,  load average: 5.08, 4.66, 4.59
+ ff=default
+ image=yegor256/rultor-image:1.3
+ rebase=false
+ head_branch=master
+ pull_title='(#1088) Improve test coverage'
+ author=paulodamaso
+ directory=
+ head=git@github.com:yegor256/takes.git
+ pull_id=1094
+ fork=git@github.com:baudoliver7/takes.git
+ fork_branch=improve_test_coverage
+ squash=false
+ vars=('--env=head=git@github.com:yegor256/takes.git' '--env=pull_id=1094' '--env=fork=git@github.com:baudoliver7/takes.git' '--env=fork_branch=improve_test_coverage' '--env=head_branch=master' '--env=pull_title=(#1088) Improve test coverage' '--env=author=paulodamaso' '--env=scripts=( '\''export '\''\'\'''\''head=git@github.com:yegor256/takes.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''pull_id=1094'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''fork=git@github.com:baudoliver7/takes.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''fork_branch=improve_test_coverage'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''head_branch=master'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''pull_title=(#1088) Improve test coverage'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''author=paulodamaso'\''\'\'''\'''\'' '\'';'\'' '\''sudo update-java-alternatives -s java-1.8.0-openjdk-amd64'\'' '\'';'\'' '\''export LC_ALL=en_US.UTF-8'\'' '\'';'\'' '\''export LANG=en_US.UTF-8'\'' '\'';'\'' '\''export LANGUAGE=en_US.UTF-8'\'' '\'';'\'' '\''mvn clean install -Pqulice --errors --settings ../settings.xml'\'' '\'';'\'' '\''mvn clean site -Psite --errors --settings ../settings.xml'\'' '\'';'\'' '\''pdd --source=$(pwd) --verbose --file=/dev/null'\'' '\'';'\'' )')
+ scripts=('export '\''head=git@github.com:yegor256/takes.git'\''' ';' 'export '\''pull_id=1094'\''' ';' 'export '\''fork=git@github.com:baudoliver7/takes.git'\''' ';' 'export '\''fork_branch=improve_test_coverage'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_title=(#1088) Improve test coverage'\''' ';' 'export '\''author=paulodamaso'\''' ';' 'sudo update-java-alternatives -s java-1.8.0-openjdk-amd64' ';' 'export LC_ALL=en_US.UTF-8' ';' 'export LANG=en_US.UTF-8' ';' 'export LANGUAGE=en_US.UTF-8' ';' 'mvn clean install -Pqulice --errors --settings ../settings.xml' ';' 'mvn clean site -Psite --errors --settings ../settings.xml' ';' 'pdd --source=$(pwd) --verbose --file=/dev/null' ';')
+ container=yegor256_takes_1094
+ as_root=false
+ mkdir -p /home/rultor/.ssh
+ echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
+ chmod 600 /home/rultor/.ssh/config
+ git clone git@github.com:yegor256/takes.git repo
Cloning into 'repo'...
+ cd repo
+ git config user.email me@rultor.com
+ git config user.name rultor
+ '[' -z 'export '\''head=git@github.com:yegor256/takes.git'\''' ']'
+ cd ..
+ cat
+ '[' false = true ']'
+ cat
+ chmod a+x entry.sh
+ cat
+ echo 'export '\''head=git@github.com:yegor256/takes.git'\''' ';' 'export '\''pull_id=1094'\''' ';' 'export '\''fork=git@github.com:baudoliver7/takes.git'\''' ';' 'export '\''fork_branch=improve_test_coverage'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_title=(#1088) Improve test coverage'\''' ';' 'export '\''author=paulodamaso'\''' ';' 'sudo update-java-alternatives -s java-1.8.0-openjdk-amd64' ';' 'export LC_ALL=en_US.UTF-8' ';' 'export LANG=en_US.UTF-8' ';' 'export LANGUAGE=en_US.UTF-8' ';' 'mvn clean install -Pqulice --errors --settings ../settings.xml' ';' 'mvn clean site -Psite --errors --settings ../settings.xml' ';' 'pdd --source=$(pwd) --verbose --file=/dev/null' ';'
+ sensitive=()
+ gpgconf --reload gpg-agent
+ gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
?: pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
'cid' file is absent, container wasn't started correctly
```

2021-06-23 21:16 UTC, paulodamaso commented
@rultor merge

2021-06-23 21:17 UTC, rultor commented
> @rultor merge

@paulodamaso OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24654-867165099)

2021-06-23 21:19 UTC, rultor commented
> @rultor merge

@baudoliver7 @paulodamaso Oops, I failed. You can see the full log [here](https://www.rultor.com/t/24654-867165099) (spent 2min)

```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 30166
+ echo '1.69.1 839260fab'
1.69.1 839260fab
+ date
Wed Jun 23 23:17:54 CEST 2021
+ uptime
 23:17:54 up 269 days,  7:23,  0 users,  load average: 4.84, 4.66, 4.60
+ ff=default
+ image=yegor256/rultor-image:1.3
+ rebase=false
+ head_branch=master
+ pull_title='(#1088) Improve test coverage'
+ author=paulodamaso
+ directory=
+ head=git@github.com:yegor256/takes.git
+ pull_id=1094
+ fork=git@github.com:baudoliver7/takes.git
+ fork_branch=improve_test_coverage
+ squash=false
+ vars=('--env=head=git@github.com:yegor256/takes.git' '--env=pull_id=1094' '--env=fork=git@github.com:baudoliver7/takes.git' '--env=fork_branch=improve_test_coverage' '--env=head_branch=master' '--env=pull_title=(#1088) Improve test coverage' '--env=author=paulodamaso' '--env=scripts=( '\''export '\''\'\'''\''head=git@github.com:yegor256/takes.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''pull_id=1094'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''fork=git@github.com:baudoliver7/takes.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''fork_branch=improve_test_coverage'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''head_branch=master'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''pull_title=(#1088) Improve test coverage'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''author=paulodamaso'\''\'\'''\'''\'' '\'';'\'' '\''sudo update-java-alternatives -s java-1.8.0-openjdk-amd64'\'' '\'';'\'' '\''export LC_ALL=en_US.UTF-8'\'' '\'';'\'' '\''export LANG=en_US.UTF-8'\'' '\'';'\'' '\''export LANGUAGE=en_US.UTF-8'\'' '\'';'\'' '\''mvn clean install -Pqulice --errors --settings ../settings.xml'\'' '\'';'\'' '\''mvn clean site -Psite --errors --settings ../settings.xml'\'' '\'';'\'' '\''pdd --source=$(pwd) --verbose --file=/dev/null'\'' '\'';'\'' )')
+ scripts=('export '\''head=git@github.com:yegor256/takes.git'\''' ';' 'export '\''pull_id=1094'\''' ';' 'export '\''fork=git@github.com:baudoliver7/takes.git'\''' ';' 'export '\''fork_branch=improve_test_coverage'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_title=(#1088) Improve test coverage'\''' ';' 'export '\''author=paulodamaso'\''' ';' 'sudo update-java-alternatives -s java-1.8.0-openjdk-amd64' ';' 'export LC_ALL=en_US.UTF-8' ';' 'export LANG=en_US.UTF-8' ';' 'export LANGUAGE=en_US.UTF-8' ';' 'mvn clean install -Pqulice --errors --settings ../settings.xml' ';' 'mvn clean site -Psite --errors --settings ../settings.xml' ';' 'pdd --source=$(pwd) --verbose --file=/dev/null' ';')
+ container=yegor256_takes_1094
+ as_root=false
+ mkdir -p /home/rultor/.ssh
+ echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
+ chmod 600 /home/rultor/.ssh/config
+ git clone git@github.com:yegor256/takes.git repo
Cloning into 'repo'...
+ cd repo
+ git config user.email me@rultor.com
+ git config user.name rultor
+ '[' -z 'export '\''head=git@github.com:yegor256/takes.git'\''' ']'
+ cd ..
+ cat
+ '[' false = true ']'
+ cat
+ chmod a+x entry.sh
+ cat
+ echo 'export '\''head=git@github.com:yegor256/takes.git'\''' ';' 'export '\''pull_id=1094'\''' ';' 'export '\''fork=git@github.com:baudoliver7/takes.git'\''' ';' 'export '\''fork_branch=improve_test_coverage'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_title=(#1088) Improve test coverage'\''' ';' 'export '\''author=paulodamaso'\''' ';' 'sudo update-java-alternatives -s java-1.8.0-openjdk-amd64' ';' 'export LC_ALL=en_US.UTF-8' ';' 'export LANG=en_US.UTF-8' ';' 'export LANGUAGE=en_US.UTF-8' ';' 'mvn clean install -Pqulice --errors --settings ../settings.xml' ';' 'mvn clean site -Psite --errors --settings ../settings.xml' ';' 'pdd --source=$(pwd) --verbose --file=/dev/null' ';'
+ sensitive=()
+ gpgconf --reload gpg-agent
+ gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
?: pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
'cid' file is absent, container wasn't started correctly
```

2021-06-23 21:21 UTC, paulodamaso commented
@rultor merge

2021-06-23 21:22 UTC, rultor commented
> @rultor merge

@paulodamaso OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24654-867168124)

2021-06-23 21:24 UTC, rultor commented
> @rultor merge

@baudoliver7 @paulodamaso Oops, I failed. You can see the full log [here](https://www.rultor.com/t/24654-867168124) (spent 2min)

```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 31196
+ echo '1.69.1 839260fab'
1.69.1 839260fab
+ date
Wed Jun 23 23:23:23 CEST 2021
+ uptime
 23:23:23 up 269 days,  7:29,  0 users,  load average: 4.62, 4.59, 4.57
+ ff=default
+ image=yegor256/rultor-image:1.3
+ rebase=false
+ head_branch=master
+ pull_title='(#1088) Improve test coverage'
+ author=paulodamaso
+ directory=
+ head=git@github.com:yegor256/takes.git
+ pull_id=1094
+ fork=git@github.com:baudoliver7/takes.git
+ fork_branch=improve_test_coverage
+ squash=false
+ vars=('--env=head=git@github.com:yegor256/takes.git' '--env=pull_id=1094' '--env=fork=git@github.com:baudoliver7/takes.git' '--env=fork_branch=improve_test_coverage' '--env=head_branch=master' '--env=pull_title=(#1088) Improve test coverage' '--env=author=paulodamaso' '--env=scripts=( '\''export '\''\'\'''\''head=git@github.com:yegor256/takes.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''pull_id=1094'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''fork=git@github.com:baudoliver7/takes.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''fork_branch=improve_test_coverage'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''head_branch=master'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''pull_title=(#1088) Improve test coverage'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''author=paulodamaso'\''\'\'''\'''\'' '\'';'\'' '\''sudo update-java-alternatives -s java-1.8.0-openjdk-amd64'\'' '\'';'\'' '\''export LC_ALL=en_US.UTF-8'\'' '\'';'\'' '\''export LANG=en_US.UTF-8'\'' '\'';'\'' '\''export LANGUAGE=en_US.UTF-8'\'' '\'';'\'' '\''mvn clean install -Pqulice --errors --settings ../settings.xml'\'' '\'';'\'' '\''mvn clean site -Psite --errors --settings ../settings.xml'\'' '\'';'\'' '\''pdd --source=$(pwd) --verbose --file=/dev/null'\'' '\'';'\'' )')
+ scripts=('export '\''head=git@github.com:yegor256/takes.git'\''' ';' 'export '\''pull_id=1094'\''' ';' 'export '\''fork=git@github.com:baudoliver7/takes.git'\''' ';' 'export '\''fork_branch=improve_test_coverage'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_title=(#1088) Improve test coverage'\''' ';' 'export '\''author=paulodamaso'\''' ';' 'sudo update-java-alternatives -s java-1.8.0-openjdk-amd64' ';' 'export LC_ALL=en_US.UTF-8' ';' 'export LANG=en_US.UTF-8' ';' 'export LANGUAGE=en_US.UTF-8' ';' 'mvn clean install -Pqulice --errors --settings ../settings.xml' ';' 'mvn clean site -Psite --errors --settings ../settings.xml' ';' 'pdd --source=$(pwd) --verbose --file=/dev/null' ';')
+ container=yegor256_takes_1094
+ as_root=false
+ mkdir -p /home/rultor/.ssh
+ echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
+ chmod 600 /home/rultor/.ssh/config
+ git clone git@github.com:yegor256/takes.git repo
Cloning into 'repo'...
+ cd repo
+ git config user.email me@rultor.com
+ git config user.name rultor
+ '[' -z 'export '\''head=git@github.com:yegor256/takes.git'\''' ']'
+ cd ..
+ cat
+ '[' false = true ']'
+ cat
+ chmod a+x entry.sh
+ cat
+ echo 'export '\''head=git@github.com:yegor256/takes.git'\''' ';' 'export '\''pull_id=1094'\''' ';' 'export '\''fork=git@github.com:baudoliver7/takes.git'\''' ';' 'export '\''fork_branch=improve_test_coverage'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_title=(#1088) Improve test coverage'\''' ';' 'export '\''author=paulodamaso'\''' ';' 'sudo update-java-alternatives -s java-1.8.0-openjdk-amd64' ';' 'export LC_ALL=en_US.UTF-8' ';' 'export LANG=en_US.UTF-8' ';' 'export LANGUAGE=en_US.UTF-8' ';' 'mvn clean install -Pqulice --errors --settings ../settings.xml' ';' 'mvn clean site -Psite --errors --settings ../settings.xml' ';' 'pdd --source=$(pwd) --verbose --file=/dev/null' ';'
+ sensitive=()
+ gpgconf --reload gpg-agent
+ gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
?: pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
'cid' file is absent, container wasn't started correctly
```

2021-09-08 09:41 UTC, baudoliver7 commented
@yegor256 could you check/merge this PR please ? It has been approved by @andreoss.

2021-09-17 10:05 UTC, baudoliver7 commented
@yegor256 Please, could you merge now ? Previous mergers failed because of rultor troubles. But it has been solved.

2021-11-03 13:58 UTC, baudoliver7 commented
@yegor256 please, have a look on my suggestion.

2021-11-14 05:37 UTC, yegor256 commented
@rultor merge

2021-11-14 05:37 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24654-968210454)

2021-11-14 05:40 UTC, rultor commented
> @rultor merge

@baudoliver7 @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/24654-968210454) (spent 3min)

```
[\u001b[1;31mERROR\u001b[m] \u001b[1;31m\u001b[m
[\u001b[1;31mERROR\u001b[m] -> \u001b[1m[Help 1]\u001b[m
\u001b[1;31morg.apache.maven.lifecycle.LifecycleExecutionException\u001b[m: \u001b[1;31mFailed to execute goal \u001b[32morg.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile\u001b[m \u001b[1m(default-testCompile)\u001b[m on project \u001b[36mtakes\u001b[m: \u001b[1;31mCompilation failure
/home/r/repo/src/test/java/org/takes/rs/xe/XeWhenTest.java:[143,23] unreported exception java.lang.Exception; must be caught or declared to be thrown
\u001b[m\u001b[m
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:215\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:957\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:289\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:193\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
\u001b[1mCaused by\u001b[m: org.apache.maven.plugin.compiler.CompilationFailureException: \u001b[1;31mCompilation failure
/home/r/repo/src/test/java/org/takes/rs/xe/XeWhenTest.java:[143,23] unreported exception java.lang.Exception; must be caught or declared to be thrown
\u001b[m
    \u001b[1mat\u001b[m org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (\u001b[1mAbstractCompilerMojo.java:1220\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.compiler.TestCompilerMojo.execute (\u001b[1mTestCompilerMojo.java:180\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (\u001b[1mDefaultBuildPluginManager.java:137\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:210\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:957\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:289\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:193\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] Re-run Maven using the \u001b[1m-X\u001b[m switch to enable full debug logging.
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] For more information about the errors and possible solutions, please read the following articles:
[\u001b[1;31mERROR\u001b[m] \u001b[1m[Help 1]\u001b[m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
container 7eb31c015c9db84f8b335a7c0ac63a27d523ac6790066774a833692c346f3f33 is dead
Sun Nov 14 06:40:37 CET 2021
```

2021-11-14 05:42 UTC, yegor256 commented
@baudoliver7 check your code, it seems that the defect is there

2021-11-14 23:59 UTC, baudoliver7 commented
@yegor256 fixed now. Could you try again ?

2021-11-15 04:18 UTC, yegor256 commented
@rultor merge

2021-11-15 04:19 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24654-968523275)

2021-11-15 04:31 UTC, rultor commented
> @rultor merge

@baudoliver7 @yegor256 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/24654-968523275) (spent 12min)

```
    \u001b[1mat\u001b[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (\u001b[1mDefaultBuildPluginManager.java:137\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:210\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:957\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:289\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:193\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
\u001b[1mCaused by\u001b[m: java.io.IOException: \u001b[1;31mThe environment variable JAVA_HOME is not correctly set.\u001b[m
    \u001b[1mat\u001b[m org.apache.maven.plugin.javadoc.AbstractJavadocMojo.getJavadocExecutable (\u001b[1mAbstractJavadocMojo.java:3672\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport (\u001b[1mAbstractJavadocMojo.java:1945\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.javadoc.JavadocReport.generate (\u001b[1mJavadocReport.java:130\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument (\u001b[1mReportDocumentRenderer.java:233\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule (\u001b[1mDefaultSiteRenderer.java:311\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (\u001b[1mDefaultSiteRenderer.java:129\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.site.render.SiteMojo.renderLocale (\u001b[1mSiteMojo.java:182\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.site.render.SiteMojo.execute (\u001b[1mSiteMojo.java:141\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (\u001b[1mDefaultBuildPluginManager.java:137\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:210\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:957\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:289\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:193\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] Re-run Maven using the \u001b[1m-X\u001b[m switch to enable full debug logging.
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] For more information about the errors and possible solutions, please read the following articles:
[\u001b[1;31mERROR\u001b[m] \u001b[1m[Help 1]\u001b[m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
container 43a4c048017579c5b5c6ec22935a536c545af780a51d97753ca8d0c892d6819e is dead
Mon Nov 15 05:31:19 CET 2021
```

2021-11-15 05:45 UTC, yegor256 commented
@rultor merge

2021-11-15 05:46 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24654-968558490)

2021-11-15 05:59 UTC, merged

2021-11-15 05:59 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/24654-968558490) (took me 13min)

2021-11-15 06:09 UTC, yegor256 commented
@baudoliver7 thanks!

2021-11-27 03:02 UTC, 0crat commented
@andreoss[/z](https://www.0crat.com/u/andreoss) resigned from [#1094](https://github.com/yegor256/takes/issues/1094), since the job is not in scope anymore

<!-- https://www.0crat.com/footprint/C3FFK3YAY/36c97a85-ecc5-44ca-903d-72bafc917ea4, version: 0.55.1, hash: ${buildNumber} -->