(#997) Introduce a test to show bug
yegor256/takes pull request #1101
Opened 2021-04-17 15:09 UTC by baudoliver7

For #997 :

- Create `CopyBytesUntilBoundary` to extract `copy` function
- Introduce a test to show bug

2021-04-18 21:58 UTC, andreoss requested changes

2021-04-19 04:50 UTC, baudoliver7 commented on src/test/java/org/takes/rq/multipart/CopyBytesUntilBoundaryTest.java
> +public final class CopyBytesUntilBoundaryTest {
@andreoss Done.

2021-04-19 04:54 UTC, baudoliver7 commented
@andreoss Please, see my changes.

2021-04-24 15:57 UTC, andreoss approved these changes

2021-04-29 01:22 UTC, baudoliver7 commented
@paulodamaso Could you check/merge ? Work has been approved by @andreoss.

2021-09-01 17:26 UTC, yegor256 commented
@rultor merge

2021-09-01 17:46 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24997-910496262)

2021-09-01 17:55 UTC, merged

2021-09-01 17:56 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/24997-910496262) (took me 10min)

2021-09-01 18:23 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/C3FFK3YAY/68a9ab78-430e-4db2-811d-ac566276bc5e, version: 0.55.1, hash: ${buildNumber} -->

2021-09-01 18:30 UTC, sereshqua commented
@andreoss please make sure you will find at least 3 issues during next CR, thanks

2021-09-01 18:30 UTC, sereshqua commented
@0crat quality acceptable

2021-09-01 18:31 UTC, 0crat commented
Code review was too long (137 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

<!-- https://www.0crat.com/footprint/C3FFK3YAY/3641811c-fe46-4b4b-882c-94e8435a1446, version: 0.55.1, hash: ${buildNumber} -->