#895: Migrate to Junit 5
yegor256/takes pull request #1103
Opened 2021-04-26 00:50 UTC by andreoss

- Migrate to Junit 5

2021-04-26 23:16 UTC, baudoliver7 requested changes
@andreoss Please, see my comments.

2021-04-26 23:16 UTC, baudoliver7 commented on src/test/java/org/takes/facets/auth/social/PsGoogleTest.java
> +                        new Take() {
@andreoss Could you use a lambda expression ?

2021-04-26 23:16 UTC, baudoliver7 commented on src/test/java/org/takes/misc/VerboseListTest.java
>      public final ExpectedException thrown = ExpectedException.none();
@andreoss Could you use here `Assertions.assertThrows` ?

2021-04-26 23:16 UTC, baudoliver7 commented on src/test/java/org/takes/rs/RsPrintTest.java
> +                new RsPrint(new RsWithHeader("name", "\n\n\n")).asString();
@andreoss I think you don't need `{}` here.

2021-04-26 23:16 UTC, baudoliver7 commented on src/test/java/org/takes/tk/TkSlf4jTest.java
> +                new TkSlf4j(new TkFailure(new IOException(""))).act(new RqFake());
@andreoss I think you don't need `{}` in lambda expression.

2021-04-26 23:16 UTC, baudoliver7 commented on src/test/java/org/takes/tk/TkSlf4jTest.java
> +                new TkSlf4j(new TkFailure(new RuntimeException(""))).act(new RqFake());
@andreoss Ditto

2021-04-29 11:46 UTC, andreoss commented
@baudoliver7 Done

2021-09-01 17:25 UTC, yegor256 commented
@andreoss there are conflicts :(

2021-09-03 20:24 UTC, andreoss commented
@yegor256 Fixed

2021-09-04 04:19 UTC, yegor256 commented
@rultor merge

2021-09-04 04:22 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/25016-912904364)

2021-09-04 04:34 UTC, merged

2021-09-04 04:34 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/25016-912904364) (took me 11min)